version: '4.3'

services:
  db:
    restart: always
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Secret1_"
    volumes:
    ports:
      - 1433:1433