//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppCourseWork.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int Id { get; set; }
        public int IdProductSale { get; set; }
        public Nullable<int> IdUser { get; set; }
        public decimal Cost { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual ProductSale ProductSale { get; set; }
        public virtual User User { get; set; }
    }
}
